name: CI

on:
  push:
    branches: [ master ]
    paths:
        - '*.xml'
        - 'Makefile'
        - 'lib/*'
  pull_request:
    branches: [ master ]
    paths:
        - '*.xml'
        - 'Makefile'
        - 'lib/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Saxon
      run: make saxonjar

    - name: Run Makefile
      run: make ci saxpath=lib/saxon.jar

    - name: Push HTML
      if: ${{ github.event_name == 'push' }}
      run: |
        git status --short draft-ietf-httpbis*.html httpbis-errata-status.html | fgrep -s " M " || exit 0
        git config --global user.name "Julian's HTML Bot"
        git config --global user.email "julian.reschke@gmx.de"
        git commit -m "generated HTML" draft-ietf-httpbis*.html
        git push
